### ISSUE TITLE
Boot fail while loading ramdisk

### ISSUE THREAD

**Issue by yulistic** [casys-kaist-internal/zjournal-kernel.code#4]
When I boot in recovery mode, I could get an error message. It says LEVEL5 paging is enabled in the kernel but CPU does not support it.

**Comment by yulistic** [comment]
Disabled related kernel config. 572fba06c

**Comment by leesecre** [comment]
May I ask which gcc-version did you use to build the kernel?

Also, how to get an error message when freeze in booting.
Just select recovery mode?

**Comment by yulistic** [comment]
gcc7 is used in Ubuntu 18.04.
